export default {
  text: "I want to address the stories told to The New York Times by five women named Abby, Rebecca, Dana, Julia who felt able to name themselves and one who did not.\rThese stories are true. At the time, I said to myself that what I did was O.K. because I never showed a woman my dick without asking first, which is also true. But what I learned later in life, too late, is that when you have power over another person, asking them to look at your dick isn’t a question. It’s a predicament for them. The power I had over these women is that they admired me. And I wielded that power irresponsibly. I have been remorseful of my actions. And I’ve tried to learn from them. And run from them. Now I’m aware of the extent of the impact of my actions. I learned yesterday the extent to which I left these women who admired me feeling badly about themselves and cautious around other men who would never have put them in that position. I also took advantage of the fact that I was widely admired in my and their community, which disabled them from sharing their story and brought hardship to them when they tried because people who look up to me didn’t want to hear it. I didn’t think that I was doing any of that because my position allowed me not to think about it. There is nothing about this that I forgive myself for. And I have to reconcile it with who I am. Which is nothing compared to the task I left them with. I wish I had reacted to their admiration of me by being a good example to them as a man and given them some guidance as a comedian, including because I admired their work.\rThe hardest regret to live with is what you’ve done to hurt someone else. And I can hardly wrap my head around the scope of hurt I brought on them. I’d be remiss to exclude the hurt that I’ve brought on people who I work with and have worked with who’s professional and personal lives have been impacted by all of this, including projects currently in production: the cast and crew of Better Things, Baskets, The Cops, One Mississippi, and I Love You, Daddy. I deeply regret that this has brought negative attention to my manager Dave Becky who only tried to mediate a situation that I caused. I’ve brought anguish and hardship to the people at FX who have given me so much The Orchard who took a chance on my movie. and every other entity that has bet on me through the years. I’ve brought pain to my family, my friends, my children and their mother.\rI have spent my long and lucky career talking and saying anything I want. I will now step back and take a long time to listen. Thank you for reading.",
  
  name: "Louis C.K.",

  date: "11/10/17",

  profession: "Actor",

  geolocation: "New York City",

  publication: "The New York Times"
}
